### PR TITLE
Pano

### PR DESCRIPTION
**Pull request by Tarotis**
@LinguList This PR includes the updates for including the Pano dataset and provides the code necessary to replicate #3

### CODE REVIEW

**Comment by LinguList** [comment]
I am not a fan of using git submodules. It is very difficult to maintain, specifically for unexperienced git users. So rather have them download data with git via the make file, please.

**Comment by LinguList** [comment]
If you indicate, where the problem with transform_alignemnts occurs, I can check. Right now, I do not know where to start and do not have the time today to check every line of the commit.

**Comment by Tarotis** [comment]
Sure, I will add the download, also for the other two datasets.

There is one difference between the Panoan dataset and the other two: There is no partial cognacy. This results in small adaptions to the `example.py` file, as you can see straight away from the changed file. I'd propose to add an argparse for a ref-variable, to set "cogid" vs "cogids". If you want, I can also include this change to the PR.

**Comment by Tarotis** [comment]
The alternative would of course be to have two different files, or to restructure the cognacy of oliveiraprotopanoan as a list during the pre-processing.

**Comment by LinguList** [comment]
Partial cognates are clearer than normal cognates. So if you label the column as "COGIDS", you get teh same result, without changing anything.

**Comment by Tarotis** [comment]
The PR now includes make-support for the full-analysis, including the download of the repositories, checking out the most recent versions (we will publish a new Pano version early next week, will update then), and combining all those commands. Tested and confirmed in a fresh environment.

I have also renamed `example-1.py` to `analysis.py`, but made no further changes to it.

The PR is now ready for review, I think @LinguList

**Comment by Tarotis** [comment]
Now the conflicts are also fixed. Hadn't updated my local branch to the changes that had been made for the initial submission.

**Comment by LinguList** [comment]
Thanks, @Tarotis. I'll merge.

**Pull request merged**
